# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
Your Code
list(a) 只會轉換第一層元素為list
tolist才能夠將多層資料型態轉換為list
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [16]:

a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a.base)
print(a.data)
print(len(a))
print(type(a))

[5 5 8 8 2 1]
1
(6,)
6
int32
4
24
None
6
<class 'numpy.ndarray'>


In [17]:
b = np.random.randint(10, size=(3,4)) 


print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)
print(b.base)
print(b.data)
print(len(b))
print(type(b))

[[0 5 2 1]
 [1 6 1 4]
 [8 2 6 3]]
2
(3, 4)
12
int32
4
48
None
3
<class 'numpy.ndarray'>


In [18]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)
print(c.base)
print(c.data)
print(len(c))
print(type(c))

[[[9 2]
  [7 1]
  [9 1]]

 [[3 1]
  [7 4]
  [3 7]]]
3
(2, 3, 2)
12
int32
4
48
None
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [12]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[9, 1, 9, 3, 1, 6]
[9, 1, 9, 3, 1, 6]


In [13]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[8, 9, 8, 3], [8, 4, 3, 9], [0, 2, 1, 8]]
[array([8, 9, 8, 3]), array([8, 4, 3, 9]), array([0, 2, 1, 8])]


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 4], [5, 9], [7, 0]], [[2, 3], [3, 6], [5, 1]]]
[array([[2, 4],
       [5, 9],
       [7, 0]]), array([[2, 3],
       [3, 6],
       [5, 1]])]


In [19]:
#簡單版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 8, 8, 2, 1]
[[0, 5, 2, 1], [1, 6, 1, 4], [8, 2, 6, 3]]
[[[9, 2], [7, 1], [9, 1]], [[3, 1], [7, 4], [3, 7]]]


In [21]:
#進階版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 8, 8, 2, 1]
[[0, 5, 2, 1], [1, 6, 1, 4], [8, 2, 6, 3]]
[[[9, 2], [7, 1], [9, 1]], [[3, 1], [7, 4], [3, 7]]]
